// NOTE: this will have to be changed if schema changes
const initialValues: Omit<Application, "_id" | "applicantID"> = {
  sections: [],
  pi: {
    firstName: "",
    lastName: "",
    position: "",
    email: "",
    institution: "",
    eRAAccount: "",
    address: "",
  },
  piAsPrimaryContact: false,
  primaryContact: {
    firstName: "",
    lastName: "",
    email: "",
    phone: "",
    role: "",
    institution: ""
  },
  additionalContacts: [],
  program: {
    name: "",
    abbreviation: "",
    description: "",
  },
  study: {
    name: "",
    abbreviation: "",
    description: "",
    publications: [],
    plannedPublications: [],
    repositories: [],
    funding: {
      agencies: [],
      grantNumbers: [],
      nciProgramOfficer: "",
      nciGPA: "",
    },
  },
  accessTypes: [],
  targetedSubmissionDate: "",
  targetedReleaseDate: "",
  timeConstraints: [],
  cancerTypes: [],
  otherCancerTypes: "",
  preCancerTypes: [],
  otherPreCancerTypes: "",
  numberOfParticipants: 0,
  species: [],
  cellLines: false,
  modelSystems: false,
  dataTypes: [],
  otherDataTypes: "",
  clinicalData: {
    dataTypes: [],
    otherDataTypes: "",
    futureDataTypes: false,
  },
  files: [],
  submitterComment: "",
  status: "New",
  programLevelApproval: false,
  reviewComment: "",
  createdAt: "",
  updatedAt: "",
  history: [],
};

export default initialValues;
