name: ESLint

on:
  workflow_dispatch:
  push:
    branches:
      - "*.*.*"
      - "main"
      - "master"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  lint:
    name: Lint Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:ci
